### ISSUE TITLE
can't generate materia theme - inkscape infinite loop

### ISSUE THREAD

**Issue by TRPB** [legend-zeratul/dotfiles-materia-nord#1]
firstly, thanks for this I was looking for a good Nord based GTK theme.

I'm running the `change-colors.sh`. Inkscape runs with 100% usage on a core and appears stuck on assets.svg. I get the following in the terminal:

```
** (org.inkscape.Inkscape:19487): WARNING **: 15:01:06.722: More than 32 iteration while updating document '/tmp/tmp.2Pt8LE7FRp/src/gtk-2.0/assets.svg'
```

and each time I kill the inkscpae process, I get the same message. It seems to be in an infinite loop. Is there any chance of just proving the generated theme?

**Comment by legend-zeratul** [comment]
Hi, I know of the issue you've mentioned - I faced the same a while back - unfortunately 1. seems to happen on a few distros only, 2. not a theme problem - more an Inkscape issue I think.. had to workaround by building the theme on Ubuntu and saving the built theme. Have added the built theme (and updated README now).

**Comment by legend-zeratul** [comment]
Sorry - wrong button - reopened - pls verify and let me know if the built theme works - will then close.

**Comment by legend-zeratul** [comment]
@TRPB Will close by Friday. Pls do let me know if you've been able to test?

**Comment by TRPB** [comment]
Thanks the prebuilt theme works great.

**Comment by legend-zeratul** [comment]
@TRPB Enjoy. Do post a screenshot if you have some time.
